# Model API Parameters
model_api_key: "api_key"     #your api key
model_base_url: "url"        #your base url
model_name: "gpt-4o-mini"    #your model name
model_temperature: 1.0       #your temperature
model_max_tokens: 700        #your max tokens

# Evaluator Parameters
eval_api_key: "api_key"      #your api key
eval_base_url: "url"         #your base url
eval_model_name: "gpt-4o-mini" #your model name
eval_temperature: 0          #your temperature
eval_max_tokens: 200         #your max tokens

# Prompt Type
prompt_type: "scp"  # Options: scp, cot, rag, rcp

# File Paths
dataset_path: "CDID.csv"
output_dir: "result"

# Start Question
start_question: 1

# 领域列表
fields:
  - "Quantum Physics"
  - "Artificial Intelligence"
  - "Biomedical Sciences"
  - "Environmental Science"
  - "Materials Science"
  - "Energy Technology"
  - "Neuroscience"
  - "Information and Communication Technology"
  - "Aerospace"
  - "Social Sciences" 